[Builtin]
	#─────────────────────────────────────────────────────────────────────────
	# This setting doesn't do anything. Change the difficulty using the in-game menu
	Difficulty = "normal"
	#─────────────────────────────────────────────────────────────────────────
	# The current version of Cold Sweat. This is used by the auto-updater
	Version = "2.4-b06e"
	#─────────────────────────────────────────────────────────────────────────
	# Allows Cold Sweat's configs to be automatically updated with new additions & formatting changes
	"Auto Update" = true

[Difficulty]
	#─────────────────────────────────────────────────────────────────────────
	# Defines the minimum habitable temperature
	# Default: 0.4
	# Range: -Infinity ~ Infinity
	"Minimum Habitable Temperature" = 0.4
	#─────────────────────────────────────────────────────────────────────────
	# Defines the maximum habitable temperature
	# Default: 1.511111111111111
	# Range: -Infinity ~ Infinity
	"Maximum Habitable Temperature" = 1.511111111111111
	#─────────────────────────────────────────────────────────────────────────
	# Rate at which the player's body temperature changes (default: 1.0 (100%))
	# Default: 1.0
	# Range: 0.0 ~ Infinity
	"Rate Multiplier" = 1.0
	#─────────────────────────────────────────────────────────────────────────
	# Damage dealt to the player when they are too hot or too cold
	# Default: 2.0
	# Range: 0.0 ~ Infinity
	"Temperature Damage" = 2.0
	#─────────────────────────────────────────────────────────────────────────
	# The time between damage (in ticks) when the player is too hot or too cold
	# Default: 40
	# Range: > 1
	"Temperature Hurt Interval" = 40
	#─────────────────────────────────────────────────────────────────────────
	# Nullifies temperature damage and effects when the difficulty is set to peaceful
	"Disable in Peaceful" = true

	["Temperature Effects".Hot]
		#─────────────────────────────────────────────────────────────────────────
		# Defines the distance at which the player's vision is obscured by heatstroke fog
		# Set to a value above 64 to disable the effect
		# Default: 6.0
		# Range: 0.0 ~ Infinity
		"Heatstroke Fog" = 6.0

	["Temperature Effects".Cold]
		#─────────────────────────────────────────────────────────────────────────
		# Up to a certain portion of the player's hearts will freeze over when they are too cold, preventing regeneration
		# Represented as a percentage in decimal form
		# Default: 0.5
		# Range: 0.0 ~ 1.0
		"Max Frozen Health Percentage" = 0.5
		#─────────────────────────────────────────────────────────────────────────
		# The player's attack knockback will be reduced by this amount when they are too cold
		# Represented as a percentage in decimal form
		# Default: 0.5
		# Range: 0.0 ~ 1.0
		"Freezing Knockback Reduction" = 0.5
		#─────────────────────────────────────────────────────────────────────────
		# The player's movement speed will be reduced by this amount when they are too cold
		# Represented as a percentage in decimal form
		# Default: 0.5
		# Range: 0.0 ~ 1.0
		"Freezing Sluggishness" = 0.5
		#─────────────────────────────────────────────────────────────────────────
		# The player's mining speed will be reduced by this amount when they are too cold
		# Represented as a percentage in decimal form
		# Default: 0.5
		# Range: 0.0 ~ 1.0
		"Freezing Mining Impairment" = 0.5

	["Temperature Effects".Acclimation]
		#─────────────────────────────────────────────────────────────────────────
		# The speed at which the player acclimates to hot or cold environments
		# Represented as MC units per minute, so a value of 0.1 = 2.5C or 4.5F per minute
		# Default: 0.0077
		# Range: 0.0 ~ Infinity
		"Acclimation Speed" = 0.0077
		#─────────────────────────────────────────────────────────────────────────
		# The offset to the player's minimum habitable temperature when they acclimate to cold (first value) or hot (second value) environments
		"Min Acclimation Range" = [-0.46, 0.23]
		#─────────────────────────────────────────────────────────────────────────
		# The offset to the player's maximum habitable temperature when they acclimate to cold (first value) or hot (second value) environments
		"Max Acclimation Range" = [-0.23, 0.46]

["Grace Period"]
	#─────────────────────────────────────────────────────────────────────────
	# The amount of time (in ticks) after the player spawns during which they are immune to temperature effects
	# Default: 6000
	# Range: > 0
	"Grace Period Length" = 6000
	#─────────────────────────────────────────────────────────────────────────
	# Enables the grace period
	"Grace Period Enabled" = true

[Misc]
	#─────────────────────────────────────────────────────────────────────────//v
	# Add TempModifier IDs to this list to disable them
	# Allows for more granular control of Cold Sweat's features
	# Run "/temp debug @s <trait>" to see IDs of all modifiers affecting the player
	# See the Cold Sweat documentation for a list of default TempModifiers
	"Disabled Temperature Modifiers" = []
	#─────────────────────────────────────────────────────────────────────────
	# Changes the update rate for temperature modifiers on entities
	# Temperature modifiers control most of Cold Sweat's behavior, so lowering this value will improve performance at the cost of responsiveness
	# Default: 1.0
	# Range: 0.1 ~ 1.0
	"Modifier Tick Rate" = 1.0
